# Generated by Django 2.2 on 2024-03-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20240330_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='is_parket',
        ),
    ]
